[package]

name = "coki"
version = "0.1.0"
authors = [ "Dan Simon <dan@dansimon.info>", "White Oak <lpzhelud@gmail.com>" ]

[dependencies]
coki_jitter = { path = "jitter" }
coki_parser = { path = "parser" }
clap = {version = "2", features = ["yaml"]}
