[package]
name = "jitter"
version = "0.1.0"
authors = ["White-Oak <lpzhelud@gmail.com>"]

[dependencies]
libc = "0.2.2"

[target.x86_64-pc-windows-gnu.dependencies]
winapi = "0.2"
kernel32-sys = "0.2"

[target.i686-pc-windows-gnu.dependencies]
winapi = "0.2"
kernel32-sys = "0.2"
